python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:1" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 20.0 > cuda1/theta-11_ori.log

python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 35 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 20.0 > cuda1/seed-5.log
python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 33 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 20.0 > cuda1/seed-3.log
python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 31 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 20.0 > cuda1/seed-1.log
python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 32 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 20.0 > cuda1/seed-2.log

python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:1" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 20.0 --add_FFN 1 > cuda1/a-FFN.log
python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:1" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 20.0 --add_residual 1 > cuda1/a-res.log
python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:1" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 20.0 --add_FFN 1 --add_residual 1 > cuda1/a-FFN-rsd.log
