# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.0 --train 1 --test_en 0
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.15 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.10 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.15 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.2 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.5 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.3 --train 0 --test_en 1 
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.4 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.6 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.8 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 1 --train 0 --test_en 1




python main.py --conf ECL-PatchTST --pred_len 720 --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 32 --test_en 0 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:05:18.802839/0/best_model.pkl"
python main.py --conf ECL-PatchTST --pred_len 720 --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 32 --test_en 1 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:05:18.802839/0/best_model.pkl"
python main.py --conf ECL-PatchTST --pred_len 720 --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 32 --test_en 2 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:05:18.802839/0/best_model.pkl"
python main.py --conf ECL-PatchTST --pred_len 720 --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 32 --test_en 3 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:05:18.802839/0/best_model.pkl"
python main.py --conf ECL-PatchTST --pred_len 720 --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 32 --test_en 4 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:05:18.802839/0/best_model.pkl"
python main.py --conf ECL-PatchTST --pred_len 720 --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 32 --test_en 5 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:05:18.802839/0/best_model.pkl"

# python main.py --conf ECL-PatchTST --pred_len 48 --noise_rate 0.5 --idx -1 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --debugger 1 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 64 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:07:30.735526/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --pred_len 48 --noise_rate 0.5 --idx -1 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --debugger 1 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name exchange_rate  --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:07:30.735526/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --pred_len 720 --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 32 --test_en 1  --refiner_residual 1 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:14:58.030042/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --pred_len 720 --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 32 --test_en 2  --refiner_residual 1 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:14:58.030042/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --pred_len 720 --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 32 --test_en 3  --refiner_residual 1 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:14:58.030042/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --pred_len 720 --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 32 --test_en 4  --refiner_residual 1 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:14:58.030042/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --pred_len 720 --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 0 --test_en 0 --theta 10 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --data_name weather --batch_size 32 --test_en 5  --refiner_residual 1 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-27-00:14:58.030042/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx --pred_len 720 -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 0 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-26-01:19:58.427225/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx --pred_len 720 -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 1 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-26-01:19:58.427225/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx --pred_len 720 -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 2 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-26-01:19:58.427225/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx --pred_len 720 -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 3 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-26-01:19:58.427225/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx --pred_len 720 -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 4 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-26-01:19:58.427225/0/best_model.pkl"
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx --pred_len 720 -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 0.8 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 5 --test_model_path "/Disk/fhyega/code/BASE/exp/ECL-PatchTST2023-08-26-01:19:58.427225/0/best_model.pkl"