# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.0 --train 1 --test_en 0
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.15 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.10 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.15 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.2 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.5 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.3 --train 0 --test_en 1 
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.4 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.6 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 0.8 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --gamma 1 --train 0 --test_en 1




# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 0
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 1
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 2
python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 3
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 4
# python main.py --conf ECL-PatchTST --noise_rate 0.5 --idx -1 --data_name ETTh2 --device "cuda:0" --seed 34 --same_init   --aligner 1 --loss huber --refiner 1 --enhance 1 --enhance_type 5 --add_noise 1 --mid_dim 128 --feature_jittering 1 --rec_intra_feature 0 --rec_ori 1 --jitter_sigma 2 --train 1 --test_en 0 --theta 1.1 --mask_border 1 --sup_weight 10.0 --ref_block_num 2 --rec_length_ratio 0.8 --train 0 --test_en 5